### ISSUE TITLE
Improved Shortener Support: Native support for Rebrandly, Filter to allow custom use

### ISSUE THREAD

**Issue by nikolay** [asdfdotdev/utm.codes#24]
Not everybody uses [Bitly](https://www.bitly.com/) and [Rebrandly](https://www.rebrandly.com/) gives more in their free tier.

**Comment by chrislarrycarl** [comment]
The shortening code could use a refactor to make it friendlier and support different services. I think it'd also be nice in addition to natively supporting different APIs to provide an easier means to use unique services (akin to what is [currently provided for links](https://github.com/christopherldotcom/utm.codes/wiki/Link-Formats), and [in progress for social sources](https://github.com/christopherldotcom/utm.codes/pull/22)).

Consider this on the roadmap. Thanks for the feedback!

**Comment by ErinPo** [comment]
Cool to know this is coming!

**Comment by chrislarrycarl** [comment]
@nikolay @ErinPo I've staged Rebrandly support in the `development` branch. There's still work to do before the next release is ready but it'd be awesome if could try out the Rebrandly support locally and share any feedback you might have. I've [started on new documentation](https://github.com/asdfdotdev/utm.codes/wiki/Rebrandly-API-Integration) but if you have any questions just let me know. Thanks!

**Comment by nikolay** [comment]
Great news, guys!

**Comment by ErinPo** [comment]
@chrislarrycarl Great news, indeed. Unfortunately,  I don't have time to test at the moment...
