### ISSUE TITLE
Suggestion: cut off links in link column on marketing links page

### ISSUE THREAD

**Issue by ErinPo** [asdfdotdev/utm.codes#26]
Displaying all the utm parameters in this location seems pointless as they are already present in the other columns where they are much more legible. It also blows up the height of rows and looks noisy.

**Comment by chrislarrycarl** [comment]
It can be handy to have the completed link available for preview. I think a good option would be to add a column for the "Link URL" value (without parameters) to the post list, then each user can select which version of the url they prefer in their Screen Options.
