### ISSUE TITLE
Alphanumeric includes hyphens?

### ISSUE THREAD

**Issue by ErinPo** [asdfdotdev/utm.codes#27]
I checked to force alphanumeric only in settings and this converted spaces to hyphens. I actually like this behavior, but it's not what people expect by the term alphanumeric. 

Personally, I prefer to use underscores as spaces and hyphens as separators like so:

`promotion_a-2019_02`

`promotion_a-2019_03`

`promotion_b-2019_02`

`promotion_b-2019_03`

This way it is easier to write regular expressions for the purpose of filtering semantically distinct portions of information that were crammed in the same utm field. I am not sure how this could be facilitated by your plugin, though as it seems semantics would need to be determined by the user... Maybe you could provide an option to transform spaces to underscores for a start (except the spaces before or after a hyphen typed by the user). Then the user would just need to be instructed to type naturally and use hyphens to separate pieces of information within fields and that would address everything, really. What do you think?

Great plugin idea, by the way!

**Comment by chrislarrycarl** [comment]
Alphanumeric should [preserve both spaces and hyphens](https://github.com/christopherldotcom/utm.codes/blob/master/classes/class-utmdotcodes.php#L1434-L1436). Remove Spaces will convert spaces to hyphens. There is [a test that should ensure spaces and hyphens are preserved](https://github.com/christopherldotcom/utm.codes/blob/master/_test/tests/test-unit.php#L182-L195) by this setting but I'll take a look at it to make sure it's behaving correctly.

A great option to replace hyphens with underscores would be to add a [utmdc_element_post_filters filter](https://github.com/christopherldotcom/utm.codes/wiki/Link-Formats) that does a character replacement on the provided value swapping hyphens for underscores.
