### ISSUE TITLE
Conceptual issues

### ISSUE THREAD

**Issue by ErinPo** [asdfdotdev/utm.codes#28]
What is the difference between saving a marketing link and publishing it? I don't see how it could make a difference given that UTM functionality operates outside of WP. Also, when using the QuickEdit function, the panel displayed appears broken / not useful, e.g. none of the fields are populated even if data is present, utm fields are missing from the panel and instead there are fields like publishing date and password protection which make no sense for managing links.

**Comment by chrislarrycarl** [comment]
Publish is the default value for the button. I'll add a filter to change that to `Save` and include it as a translatable entry in utm.codes language file. Thanks for the feedback.
