### ISSUE TITLE
Support for custom domains with url shortener services

### ISSUE THREAD

**Issue by thetacom** [asdfdotdev/utm.codes#40]
It would be useful to have the ability to specify which domain to use for the url shortening services (ie default or custom).

I manually modified line 77 of utm-dot-codes/classes/shorten/class-rebrandly.php in order to use my custom domain name for short urls instead of the default rebrand.ly domain.
`'body'        => wp_json_encode( ['domain'=>['fullName'=>'mycustomshortenerdomain'], 'destination' => $data['utmdclink_url'] . $query_string ] ),
`

**Comment by chrislarrycarl** [comment]
Thanks for the feedback @thetacom! Support for using custom domains with rebrandly will be included in v1.7.0.
